name: build-and-release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: build-and-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0      # ★ 确保拿到 tags，git describe/版本派生才正常

      # ---------- Deps ----------
      - name: Deps (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build pkg-config nsis \
                                  dpkg-dev \
                                  libx11-dev libxtst-dev libxrandr-dev libxfixes-dev
          # 如启用 Wayland portal：
          # sudo apt-get install -y libwayland-dev libglib2.0-dev

      - name: Deps (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew update
          brew install cmake ninja

      - name: Deps (Windows)
        if: startsWith(matrix.os, 'windows')
        shell: pwsh
        run: choco install -y ninja nsis

      # ---------- Configure / Build / Package ----------
      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Package (CPack)
        run: cmake --build build --target package --config Release

      # ★ 可视化：看看到底产出了什么
      - name: List outputs
        run: |
          echo "== build root =="
          ls -lah build || true
          echo "== CPack staging (if any) =="
          find build/_CPack_Packages -maxdepth 3 -type f -ls 2>/dev/null || true

      # ---------- Upload per-OS artifacts ----------
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-packages
          path: |
            build/*.deb
            build/*.zip
            build/*.txz
            build/*.tar.gz
            build/*.dmg
            build/*.pkg
            build/*.exe
            build/*.msi
            build/_CPack_Packages/**/DEB/*.deb
            build/_CPack_Packages/**/ZIP/*.zip
            build/_CPack_Packages/**/TXZ/*.txz
            build/_CPack_Packages/**/TGZ/*.tar.gz
            build/_CPack_Packages/**/Bundle/*.dmg
            build/_CPack_Packages/**/productbuild/*.pkg
          if-no-files-found: warn   # 便于发现没打出来包的 OS

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Show downloaded files
        run: |
          echo "== dist =="
          find dist -type f -maxdepth 4 -ls

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
